[package]
name = "kms_gui"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "4.4"
cosmian_crypto_core = { version = "9.3", features = ["certificate"] }
cosmian_kms_cli = { git = "https://github.com/Cosmian/kms.git", branch = "develop", package = "cosmian_kms_cli" }
cosmian_logger = { git = "https://github.com/Cosmian/kms.git", branch = "develop", package = "cosmian_logger" }
klask = { git = "https://github.com/Cosmian/klask.git" }
tokio = { version = "1.34", features = ["full"] }

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }

[profile.release]
lto = "thin"
strip = true
